RA-7
Gaileks/RecipeApp pull request #5
Opened 2024-01-28 15:15 UTC by Gaileks

2024-01-28 16:17 UTC, ievetrov requested changes

2024-01-28 16:17 UTC, ievetrov commented on app/build.gradle.kts
> +    implementation("androidx.cardview:cardview:1.0.0")
Кардвью уже есть в базовой библиотеке androidx, дполнительный импорт не требуется

2024-01-28 16:17 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +            android:layout_margin="@dimen/half_main_indent"
Правильно, что добавлены отступы. Но их сумма создает слишком большое расстояние между элементами. Больше, чем это прорисовано в макете. Давай добавлять отступы у внутренних элементов не со всех сторон

2024-01-28 16:17 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +            android:gravity="start"
Гравити отвечает за расположение элемента (а не текста внутри). А элемент закономерно занимает всю ширину карточки, не считая отступов. Так что такое позиционирование тут будет лишним

2024-01-28 16:17 UTC, ievetrov commented on app/src/main/res/values/strings.xml
> +    <string name="description_title_category">"categories title text "</string>
Строка нигде не используется, давай выпилим (в тулсах нормально хардкодить код и не тратить время условных переводчиков на отладочные данные)

2024-01-28 16:17 UTC, ievetrov commented on app/src/main/res/values/strings.xml
> +    <string name="description_title_category">"categories title text "</string>
Но описание контента должно быть (конкретно изображения)

2024-01-29 11:50 UTC, Gaileks commented on app/src/main/res/layout/item_category.xml
> +            android:layout_margin="@dimen/half_main_indent"
По макету у нас только снизу отступ 8, а везде 16?

2024-01-29 16:49 UTC, ievetrov requested changes
Отписал по отступам карточки в лс

2024-01-31 11:21 UTC, ievetrov approved these changes

2024-01-31 11:21 UTC, merged